### PR TITLE
Added check for removed function

### PR DESCRIPTION
**Pull request by 0xcrypto**
Added a check for set_magic_quotes_runtime which was throwing an undefined function error in PHP 7+
Fixes https://core.trac.wordpress.org/ticket/52074 and https://core.trac.wordpress.org/ticket/53376

### CODE REVIEW

**Comment by exprez135** [comment]
This patch is good to be applied. It fixes the deprecated function for those with PHP 7 or up. Anyone there to apply it?

**Comment by 0xcrypto** [comment]
> This patch is good to be applied. It fixes the deprecated function for those with PHP 7 or up. Anyone there to apply it?

@exprez135 it is a minor fix, not sure if it will ever make it to production. I think they are planning something new. If you need a fix for this bug, you can define a dummy function in your `functions.php` of theme or within a plugin somewhere.

```php
<?php
if (!function_exists('set_magic_quotes_runtime')) {
    function set_magic_quotes_runtime($f=null) {
        return true;
    }
}
```

**Comment by exprez135** [comment]
Thank you, 0xcrypto! Yes, I've been able to get around the problem by 
editing the plugin myself, but it would be great to have the plugin 
fixed, as it's currently broken for most people—and unless you have 
debug messages enabled, it just says a "fatal error" occurred. By 
planning something new, do you mean some sort of replacement or 
alternative?

**Comment by 0xcrypto** [comment]
@exprez135 tbh, I no longer use WordPress at work nor I am associated with any WordPress community. I just pushed this fix  as it was needed by my client at that time. If anyone from WordPress has plans, they would surely reply on https://core.trac.wordpress.org/ticket/52074. Till then it is just what it is.

**Comment by dd32** [comment]
I've broken this PR due to a force-push during some svn->git migration work. My apologies @0xcrypto.

The diff for this PR is available in the downstream fork: https://github.com/WordPress/rss-importer/compare/trunk...0xcrypto:rss-importer:patch-1

**Comment by 0xcrypto** [comment]
> I've broken this PR due to a force-push during some svn->git migration work. My apologies @0xcrypto.
> 
> The diff for this PR is available in the downstream fork: [trunk...0xcrypto:rss-importer:patch-1](https://github.com/WordPress/rss-importer/compare/trunk...0xcrypto:rss-importer:patch-1)

Its fine @dd32

**Pull request closed without merging**
